name: 'Upload localization files'
description: 'Upload localization files to SimpleLocalize translation editor'
author: "SimpleLocalize"
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  apiKey:
    description: 'Project API Key'
    required: true
    default: ''
  uploadPath:
    description: 'Which files should be uploaded'
    required: false
    default: './messages.json'
  uploadFormat:
    description: 'Choose a localization files format'
    required: false
    default: 'multi-language-json'
  uploadOptions:
    description: 'Choose additional upload options'
    required: false
    default: ''
  languageKey:
    description: 'Upload translations with language key'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - id: Setup
      run: curl -s https://get.simplelocalize.io/2.1/install | bash
      shell: bash
    - id: Execution
      shell: bash
      run: simplelocalize upload --apiKey ${{ inputs.apiKey }} --uploadPath ${{ inputs.uploadPath }} --uploadFormat ${{ inputs.uploadFormat }} ${{ inputs.uploadOptions && '--uploadOptions' }} ${{ inputs.uploadOptions }} ${{ inputs.languageKey && '--languageKey' }} ${{ inputs.languageKey }}
